server:
  port: 8888

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/dbelearning
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
file:
  storage-dir: "filestorage/images/"
  client-dir: "/images/**"
springdoc:
  swagger-ui:
    path: /